// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvpJn077wsga6K-fwDWDcYOeu80TNRuWA',
    appId: '1:611827766599:web:6b1576f750a2e0afc12862',
    messagingSenderId: '611827766599',
    projectId: 'alarma-test',
    authDomain: 'alarma-test.firebaseapp.com',
    storageBucket: 'alarma-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ZLnOlIy15oYhjNVj5PV_luGyfTIVZS8',
    appId: '1:611827766599:android:ee261776a0c93b31c12862',
    messagingSenderId: '611827766599',
    projectId: 'alarma-test',
    storageBucket: 'alarma-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAXM5YQaGVplG5uK0lrseMRye_cnBG2LQ',
    appId: '1:611827766599:ios:9ff1532b2f98d9e3c12862',
    messagingSenderId: '611827766599',
    projectId: 'alarma-test',
    storageBucket: 'alarma-test.firebasestorage.app',
    iosBundleId: 'com.example.sistemaAlarma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAXM5YQaGVplG5uK0lrseMRye_cnBG2LQ',
    appId: '1:611827766599:ios:9ff1532b2f98d9e3c12862',
    messagingSenderId: '611827766599',
    projectId: 'alarma-test',
    storageBucket: 'alarma-test.firebasestorage.app',
    iosBundleId: 'com.example.sistemaAlarma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvpJn077wsga6K-fwDWDcYOeu80TNRuWA',
    appId: '1:611827766599:web:65d5ee95ff7677f6c12862',
    messagingSenderId: '611827766599',
    projectId: 'alarma-test',
    authDomain: 'alarma-test.firebaseapp.com',
    storageBucket: 'alarma-test.firebasestorage.app',
  );
}
